global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'ecs'
    scrape_interval: 10s
    file_sd_configs:
      - names: ['/etc/prometheus/targets.yml']
